Vauxoo/odoo

- addons/web/static/src/js/view_form.js
Issue #4565 from Odoo and task 2826 from Vauxoo
> 8.0 rouding truiz

- addons/account_anglo_saxon/invoice.py
> [IMP] Adding keys to hook from when performing post processing on

- addons/stock/wizard/stock_transfer_details.py
Added the condition in the default_get of the object stock_transfer_detail to avoid create the stock pack operation always because we are losing the process made it in the packaging process
> [8.0][stock] Added condition in default_get method of stock.transfer.details object

- addons/sale_stock/sale_stock.py
For momentary solution of the speed at the moment to create invoice from  picking we replace the write of the many2many field the sale order, for a direct sql sentence.
> [8.0][sale_stock] Replace write on invoice_ids field in sale order object

- addons/stock_dropshipping/test/dropship.yml
To avoid misconfigurations,
Successfully accounting validations and have correct tracking
> [REF][stock_dropshipping] Modify dropship test with standard price equals to one

- addons/account_asset/report/account_asset_report.py
Odoo Pr:
https://github.com/odoo/odoo/pull/9128/files
> [IMP][account_asset]Better query to delay when generate view, Odoo PR 9128

- addons/stock_account/tests/test_reconciliation.py
In python it is possible that with no reason depending or some
environment variables and/or different libraries the set of a floating
pont as part of a dictionary give an unexpected result, in our case this
test which was modified were giving incorrect floating point and Odoo
already has a tool to deal with it.
Then simply we changed a forced equal in assert on unittest by the
same assert but using numbers securely passed by the float_compare tool
in odoo itself.
It closes #96
> [FIX] stock_account: Flaky test due to Floating point inaccuracy.

- addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
To connect the PosBox into a VPN, is required this package
> [IMP] point_of_sale: added OpenVPN to packages to install list

- addons/hw_posbox_vpn/__init__.py
- addons/hw_posbox_vpn/__openerp__.py
- addons/hw_posbox_vpn/controllers/__init__.py
- addons/hw_posbox_vpn/controllers/main.py
- addons/point_of_sale/tools/posbox/configuration/odoo.conf
- addons/point_of_sale/tools/posbox/configuration/posbox_vpn_upload.sh
- addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
- addons/point_of_sale/tools/posbox/overwrite_before_init/etc/openvpn/pos.conf
- addons/point_of_sale/tools/posbox/posbox_create_image.sh
This calls a script named posbox_vpn_upload.sh, which will request a .conf extension file to be copied in PosBox home path, and then, will  restart the openvpn service.
**Symbolic Link (Before)**
**Password empty**
**Wrong password**
**Uploading file**
**Restarting VPN**
**Symbolic link (After)**
> [IMP] hw_posbox_vpn: new process to upload vpn configuration file

- addons/l10n_mx/data/account_chart.xml
- addons/l10n_mx/data/account_tax.xml
Changed the mexican chart template by the accounts provided by the SAT
in electronic accounting, in this file: http://goo.gl/7Olr4J
This change update all accounts and the taxes account
> [IMP] l10n_mx: Changed Mexican Chart Template.

- addons/l10n_mx/data/account_tag.xml
Completed color in parent tags according to SAT Catalog.
This Colors was removed by error in the last commit.
> [IMP] l10n_mx: Completed tag color in parent SAT accounts

- addons/base_address_structured/__init__.py
- addons/base_address_structured/__manifest__.py
- addons/base_address_structured/models/__init__.py
- addons/base_address_structured/models/base_address_structured.py
- addons/base_address_structured/views/base_address_structured.xml
- addons/web/static/src/less/form_view.less
Merging https://github.com/odoo/odoo/pull/13835
> 10 odoo address structured fp

- addons/base_vat/models/res_partner.py
- odoo/addons/base/res/res_partner.py
Cherry-pick from https://github.com/odoo/odoo/commit/f430736b796d0204dcc5c0231113b1c5dd9d67f6
Fix the warning https://github.com/Vauxoo/mexico/issues/324
> [FIX] base, base_vat: constrains decorator does support only directs fields

- addons/l10n_mx/data/account_tag_data.xml
> [FIX] l10n_mx: Fixed tag that have not correct name.

- addons/stock/procurement.py
To be able to undertake issue 218 it is necessary to make this PR to bring us
the modifications made by @moylop260 in https://github.com/odoo/odoo/pull/13636
> [ADD]PR to Vx odoo 8.0 from odoo/odoo#8.0

- addons/l10n_mx/__manifest__.py
- addons/l10n_mx/data/fiscal_position_data.xml
vauxoo/mexico
https://github.com/Vauxoo/mexico/blob/10.0/l10n_mx_base/data/fiscal_position_data.xml
Fixes https://github.com/Vauxoo/mexico/issues/524
> [IMP] l10n_mx: Moved fiscal position data used like fiscal regime from

- addons/l10n_mx/data/l10n_mx_chart_data.xml
- addons/l10n_mx/models/chart_template.py
To complete the Tax configuration to cash basis are assigned the
account "216.10.13" in some taxes, but this account is not created
Changed account by 216.10.20
> [IMP] l10n_mx: Fixed code in account

- addons/base_address_city/__init__.py
- addons/base_address_city/__manifest__.py
- addons/base_address_city/models/__init__.py
- addons/base_address_city/models/res_city.py
- addons/base_address_city/models/res_country.py
- addons/base_address_city/models/res_partner.py
- addons/base_address_city/security/ir.model.access.csv
- addons/base_address_city/views/res_city_view.xml
- addons/base_address_city/views/res_country_view.xml
- addons/base_address_extended/__init__.py
- addons/base_address_extended/__manifest__.py
- addons/base_address_extended/models/__init__.py
- addons/base_address_extended/models/base_address_extended.py
- addons/base_address_extended/tests/__init__.py
- addons/base_address_extended/tests/test_street_fields.py
- addons/base_address_extended/views/base_address_extended.xml
- addons/base_vat/models/res_partner.py
- addons/crm/models/crm_lead.py
- addons/l10n_mx/__manifest__.py
- addons/l10n_mx/data/account_data.xml
- addons/l10n_mx/data/account_tax_data.xml
- addons/l10n_mx/data/l10n_mx_chart_data.xml
- addons/l10n_mx/models/chart_template.py
- addons/web/static/src/less/form_view.less
- odoo/addons/base/res/res_country.py
- odoo/addons/base/res/res_country_view.xml
- odoo/addons/base/res/res_partner.py
- odoo/models.py
TODO
---------
https://github.com/Vauxoo/odoo/commit/0757c1fc865661f9f981ed1752bf2708b9a0dc9b
https://github.com/Vauxoo/odoo/commit/9411d81efe780499a58c7861e76cf3691918a58d
https://github.com/Vauxoo/odoo/commit/ae621ed9468c185f168190b28d0de1907207012a
https://github.com/Vauxoo/odoo/commit/3c1766657948bfa3652f5ed5cecd7168032be9ba
https://github.com/Vauxoo/odoo/commit/4f7490ffedd9b270d3dcb8c54a3665b7795fc3cc
https://github.com/Vauxoo/odoo/commit/e8d5170c154d5dff589a6c3263c7d2e81f407f9d
https://github.com/Vauxoo/odoo/commit/40a4c9c25ed6d186d41e03ccb711f7883e9746f1
[IMP] base_vat: allow to re-use the 'vat' field of res.partner for lo…  …			19b2fb6
[FIX] base, base_vat: constrains decorator does support only directs …  …			c3840b2
[IMP] l10n_mx: Added missing account in chart template.  … …
> [FIX] Cherry-pick to base_address_* modules from Odoo master

- addons/product/pricelist.py
VX#6769
The pricelist.py file is modified so that you can apply the list according to
conditional given via data ir.config_parameter directly related to the
PR https://github.com/Vauxoo/typ/pull/237
> [ADD] product: conditioned price according to ir.config_parameter

- addons/website_sale/models/sale_order.py
in order to fix https://github.com/Vauxoo/abastotal/issues/87
and https://github.com/odoo/odoo/issues/15903
this pr made a cherry pick from this pr https://github.com/odoo/odoo/pull/16145
This is the Cherry pick of 2906243c4fc58fa97e098dae2e90faf614fdef29
Dummy pr
https://github.com/Vauxoo/abastotal/pull/261
> [FIX] Redirection to confirmation page at the end of the checkout process in case of a previous cart reset by the user. HU#1572 TA#7876

- addons/l10n_mx/__manifest__.py
- addons/l10n_mx/data/fiscal_position_data.xml
Based on [odoo/saas-14](https://github.com/odoo/odoo/blob/saas-14/addons/l10n_mx/data/fiscal_position_data.xml#L34) data.
> [IMP] l10n_mx: Data added to fiscal position to sale & purchase

- addons/base_address_extended/i18n/es.po
Task [#8017](https://www.vauxoo.com/web#id=8017&view_type=form&model=project.task&menu_id=136&action=138) coming from issue fixed for versión 9.0 [#581](https://github.com/Vauxoo/mexico/issues/581)
> [10.0][ADD] Extended Addresses translation added

- addons/base_address_city/models/res_partner.py
- addons/base_address_extended/views/base_address_extended.xml
- odoo/addons/base/res/res_partner_view.xml
This PR is for the last five cherry picks of https://github.com/Vauxoo/odoo/commits/master/addons/base_address_city/models/res_partner.py to fix problems with the res.partner.city_id
> [FIX] base_address_city: _fields_view_get() now working properly

- addons/l10n_mx/models/account.py
Issue: https://github.com/Vauxoo/mexico/issues/746
DUMMY: https://github.com/Vauxoo/mexico/pull/766
Result:
- Tags that does not match with 'code' are removed.
https://drive.google.com/open?id=0B4jIZfjtBteKRGVTNV9saTZ4Z2s
> [REF] l10n_mx: Onchange delete tag_ids when you change code in account.account issue#746

- odoo/addons/base/ir/ir_translation.py
It was decided to do this patch when talking to @moylop260 
FIX https://github.com/odoo/odoo/issues/18363
Odoo Ticket 766.489
> [FIX] odoo: Temporal patch to`support` spanish Latin America (es_419) lang

- addons/l10n_mx/data/account_tag_data.xml
These changes were announced in the new Annex 24 RFM 2019 [1] and define
the new code for  accounts for the northern border zone. This change affects a
part of the CoA because these accounts were changed from the middile to the
end of the group.
[1] https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1461173776384&ssbinary=true
--
> [FIX] l10n_mx: add new changes on COA according with the SAT

- addons/stock/models/procurement.py
When the stock scheduler is run, one of the executed tasks is to reserve
all possible moves. The domain used to determine what moves to reserve,
unless recent versions, is harcoded.
This makes possible to inherit that behavior.
This is a backport of 027ff77a9e11.
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
--
> [IMP] stock: Make inheritable domain to reserve moves on scheduler
