Vauxoo/odoo

addons/stock/stock.py
Modified the method to get the quants related to a package, because this methos does not allow to use the same package in differents pickings. This change avoids to returs all quants if the products in the quant is no a product related to the current picking
=> [8.0][stock] Changed the method to get the quants related to a package

addons/purchase/purchase.py
[FIX] When sending a message purchase does not check for state of record
which can lead to revert the state of the purchase order back to sent if
it was meant to be in another state
=> [FIX] When sending a message purchase does not check for state of record

addons/stock/stock.py
When you have more than one line with the same product and one of these lines is in waiting state can bring problem because is considered at the moment generate the new link in the model stock_move_operation_link. For this reason the move with waiting state must be bypassed
=> [8.0][stock] Avoiding move with waiting state at the moment to create the stock_move_operation_link objects

addons/stock_account/stock.py
When invoicing based on delivery lines, the system used
to group lines per partner, currency, *and* salesman, in
order to assign the corresponding salesman on the invoice.
However this creates multiple invoices for the same
customer, quite annoying for some businesses.
Assigning the invoice to the user creating it fixes this
problem and makes sense business-wise too.
In the future we could possibly assign a different
salesman to each invoice line, for reporting purposes
(e.g. for sales commissions)
=> [FIX] stock_account: do not group move lines to invoices per saleman

addons/account_asset/account_asset_invoice.py
The field period_id didn't exist in model "account.asset.asset"
Closes: #11262
opw:671494
=> [FIX] account_asset: period_id field

addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh, addons/point_of_sale/tools/posbox/posbox_download_images.sh
The issue odoo/odoo#12650 reports that no kernel modules are
installed when run script to create posbox image, and this is
caused because the command 'modprobe' who adds/removes modules
from the Linux kernel not find the modules directory:
'/lib/modules/(uname -r)'
To solve this issue was changed the script to download raspbian
image, replacing the raspbian link by another with a fixed kernel
version (4.1.19-v7+).
Also to ensure that '/lib/modules/(uname -r)' exists was used
rpi-update GIT-HASH to install a specific firmware-kernel version
About rpi-update:
https://tech.enekochan.com/en/2014/03/08/upgradedowngrade-to-a-specific-firmware-kernel-version-with-rpi-update-in-raspbian/
About command 'modprobe':
http://www.computerhope.com/unix/modprobe.htm
=> [FIX] point_of_sale: solved issue about kernel modules not loaded

addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
We don't mount /boot in fstab to prevent systemd-udev looking for
corresponding kernel modules in /lib/modules. We need to do this
because the modified kernel-qemu image we use for emulation is usually
not 100% the same version as in the Raspbian image. Therefore
systemd-udev won't be able to find the 'correct' kernel modules in
/lib/modules.
This causes issues when the raspberrypi-kernel package is updated
however. apt will update /lib/modules and will write the new
kernel{7,}.img files to /boot. Before this patch /boot was just a
directory on /dev/sda2, not the 'real' /boot which is on /dev/sda1. So
you'd end up with old, not updated kernel images but new, updated
kernel modules in /lib/modules.
This mounts /boot after the system booted. /boot gets mapped to
/dev/sda1 by …
=> [FIX] point_of_sale: mount /boot when building the POSBox image

addons/point_of_sale/tools/posbox/posbox_create_image.sh
Why this PR?
-------------
When adding/removing partitions using kpartx, is recommended wait a couple of seconds before running some other command that can assume that partitions are now gone or still yet. Otherwise, maybe could appear a error of this kind: '<COMMAND_NAME> /path/to/device failed: Device or resource busy'.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734794
=> [FIX] point_of_sale: avoid partition read error when building the PosBox image

addons/l10n_mx/__openerp__.py, addons/l10n_mx/data/account_chart.xml, addons/l10n_mx/data/account_tag.xml, addons/l10n_mx/data/account_tax.xml
Assigned the account tags with data data in the Mexican chart template.
Created the account tag data based in this [document](http://www.sat.gob.mx/fichas_tematicas/buzon_tributario/Documents/codigo_agrupador.pdf), where each account parent is a new tag in this data.
The name is the concatenation of tag.code + tag.name, because the account.tag model have not the code field.
The green color is assigned to this tags.
Fix account in tax data.
=> [IMP] l10n_mx: Account tags in chart template

addons/l10n_mx/__openerp__.py, addons/l10n_mx/data/account_chart.xml, addons/l10n_mx/data/account_journal.xml, addons/l10n_mx/data/account_tag.xml, addons/l10n_mx/data/account_tax.xml, addons/l10n_mx/data/res_company.xml, addons/l10n_mx/models/__init__.py, addons/l10n_mx/models/chart_template.py
Effectively Paid in the Mexican instances:
- Dependency to account_tax_cash_basis added, because this is the module
that have the functionality to generate the new movements.
- Added data required by new module to generate the movements of VAT
Effectively Paid.
- Fixed bad accounts and tags.
- Removed TAX by 11%, because since 2015 that tax was changed by 16%.
- Fix the account mapping to taxes.
- Inherited methods to assign the accounts needed in the taxes to IVA
Effectively Paid.
The accounts was assigned with base to this [document](https://docs.google.com/spreadsheets/d/1FXyU0fgDadAWmnAiau6lbgI9AdaO2HQN5w0YgM2FYnQ/edit#gid=0)
=> [IMP] l10n_mx: Added settings to allow apply by default the VAT

addons/stock_account/stock_account.py
price product when transfer is from 'transit' to 'internal' locations in
moves to inter warehouse
[backport master](https://github.com/odoo/odoo/blob/master/addons/stock_account/models/stock.py#L281)
[Related video in master](https://drive.google.com/file/d/0B1w9gokcJL9hRExtN3lsLWVBbWM/view)
[Related video in current version](https://drive.google.com/file/d/0B1w9gokcJL9hX3JhRTlQUnVXQ0E/view)
=> [IMP] stock_account: backport to master version to allow get average

openerp/tools/convert.py
Historically, developers had to use the `eval` attribute to set
a False value for boolean fields in XML data files:
<field name="active" eval="False"/>
This is a source of errors for beginners, who tend to provide
a string value directly, as for char/text fields.
Unfortunately string values always evaluated to `True` booleans:
<field name="active">False</field> 
This patch adds detection of some well-known falsy strings
(case-insensitive): `0`, `false`, `off`, as similarly supported
for the `noupdate` and `forcecreate` attributes of XML data records.
Closes #13152
**PR dummies:**
=> [IMP] tools: support known "falsy" string values for XML boolean fields

addons/l10n_mx/data/account_chart.xml, addons/l10n_mx/data/account_tax.xml
The ISR retentions not must be have configuration to Use Cash Basis, nor
Tax Received Account, was removed that configuration from the taxes
data.
Added account to tax effectively paid in retentions, this account is not
found in the SAT chart template, but is needed.
Assigned the new account in the taxes for retentions.
=> [IMP] l10n_mx: Remove configuration to Use Cash Basis

addons/l10n_mx/data/account_chart.xml, addons/l10n_mx/data/account_tag.xml
Generate an account tag by each account in SAT catalog, and assign to
the corresponding account.
This tags are red color.
And are created, because could be created more accounts out of SAT
catalog, and that have relation to one same tag.
Sample:
Bank1------102.01 Bancos nacionales
Bank2------102.01 Bancos nacionales
Bank3------102.01 Bancos nacionales
=> [IMP] l10n_mx: Completed tag accounts and assign in the account.

addons/l10n_mx/__init__.py, addons/l10n_mx/__manifest__.py, addons/l10n_mx/data/account_tag_data.xml, addons/l10n_mx/data/account_tax_data.xml, addons/l10n_mx/data/l10n_mx_account_journa_data.xml, addons/l10n_mx/data/l10n_mx_chart_data.xml, addons/l10n_mx/data/res_company_data.xml, addons/l10n_mx/models/__init__.py, addons/l10n_mx/models/chart_template.py
- Changed the mexican chart template by the accounts provided by the SAT
in electronic accounting, in this file: http://goo.gl/7Olr4J
- Assigned the account tags with data data in the Mexican chart
template.
- Created the account tag data based in the SAT document
(http://goo.gl/xTGz7s), where each account parent is a new tag in
this data.
The name is the concatenation of tag.code + tag.name, because
the account.tag model have not the code field.
The green color is assigned to this tags.
- Generate an account tag by each account in SAT catalog, and assign to
the corresponding account.
This tags are red color.
And are created, because could be created more accounts out of SAT
catalog, and that have relation to one same tag.
Sample:
Bank1------102.01 Bancos nacionales
Bank2------102.01 …
=> [IMP] l10n_mx: Changed Mexican Chart Template

addons/account/i18n/es.po
Translations of technical terms broke email template.
Fixes #14373
Fixes  https://github.com/Vauxoo/mexico/issues/413
Cherry-pick from https://github.com/odoo/odoo/commit/7087410c570fe10dfad4daa4431ef95f038e5531
=> [FIX] account: es translations

addons/account_tax_cash_basis/models/account_partial_reconcile.py
If there is no currency_id set on a account.move.line L, making
L.currency_id.round(5) will always be equal to 0.
opw:694660
=> [FIX] account_tax_cash_basis: function round on res.currency model

addons/point_of_sale/report/pos_order_report.py, addons/point_of_sale/report/pos_order_report_view.xml
Related to [task#6473](https://www.vauxoo.com/web#id=6473&view_type=form&model=project.task)
---
1. Update the product_qty field. Formerly was a integer field, now is a float field.
2. Add new field Unit of Measure that let us to filter the data taking into account the product unit of measure used when the product was sale.
3. Update sql operation to update the way that product_qty is compute. 
4. Compute the product uom and add a group by in order to let us filter the products using this measure.
*NOTE: First, I try to add a new product_qty_wo_conversion field and leave the product_qty field untouched. but I figured out that in a production database If I try to remove the product_qty or any column that already exist in the report view, and then I try to update the database the changes do …
=> [ADD] Point of Sale Orders Analysis now show the product qty express in product unit of measure

addons/l10n_mx/data/l10n_mx_chart_data.xml
To complete the Tax configuration to cash basis are assigned the
account "208.01.01" in some taxes, but this account is not created
https://goo.gl/7RlDQG
=> [IMP] l10n_mx: Added missing account in chart template.

addons/l10n_mx/data/account_tax_data.xml, addons/l10n_mx/models/chart_template.py
This value will be used in the XML generation and must be assigned
to sale taxes.
Could be used "IVA", "ISR" or "IEPS"
=> [IMP] l10n_mx: Assign the correct description in tax.

addons/l10n_mx/models/chart_template.py
The 'Effectively Paid' journal must be have the account '118.01.01' like debit/credit account
Fixes https://github.com/Vauxoo/odoo/issues/154
=> [FIX] l10n_mx: Assign the correct account in journal to tax basis

addons/base_address_city/__init__.py, addons/base_address_city/__manifest__.py, addons/base_address_city/models/__init__.py, addons/base_address_city/models/res_city.py, addons/base_address_city/models/res_country.py, addons/base_address_city/models/res_partner.py, addons/base_address_city/security/ir.model.access.csv, addons/base_address_city/views/res_city_view.xml, addons/base_address_city/views/res_country_view.xml, addons/base_address_extended/models/base_address_extended.py, addons/base_address_extended/tests/__init__.py, addons/base_address_extended/tests/test_street_fields.py, addons/crm/models/crm_lead.py, odoo/addons/base/res/res_country.py, odoo/addons/base/res/res_country_view.xml, odoo/addons/base/res/res_partner.py, odoo/models.py
TODO
---------
- [mail.activity.mixin](https://github.com/odoo/odoo/blob/master/addons/mail/models/mail_activity.py) is only available in master.
```python
class Lead(models.Model):
_name = "crm.lead"
_description = "Lead/Opportunity"
_order = "priority desc,date_action,id desc"
_inherit = ['mail.thread', 'ir.needaction_mixin', 'utm.mixin', 'format.address.mixin']
_mail_mass_mailing = _('Leads / Opportunities')
```
=> [REF] Cherry-pick to base_address_* modules from Odoo master

addons/product/pricelist.py
method get_param() with the self.pool.get
=> [IMP] product: in order to avoid error with old api we need to call

addons/account/views/account_invoice_view.xml, addons/account/views/report_invoice.xml, addons/sale/views/sale_views.xml
The group sale.group_discount_per_so_line is used in account but declared in
sale. As the has_group method ignores unexistant fields, this field was never
displayed until somebody install sale.
In account, replace the discount group with debug mode.
Remove it from the report as it was only displayed when at least one discount
was set (not possible if the discount field is not displayed).
In sale, makes xpath to use the correct group.
Fixes 15094
Cherry-pick from [Odoo](https://github.com/odoo/odoo/commit/c278ebf2feae649de3bfc51ec3ad0e5378816a88)
=> [FIX] sale,account: do not reference to not declared yet group

addons/l10n_cr/data/l10n_cr_state_data.xml
Summary:
--------------
To Fix:
```
2017-02-14 04:09:20,530 177 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_pvt_ltd in module base instead of l10n_cr.
2017-02-14 04:09:20,533 177 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_ltd in module base instead of l10n_cr.
2017-02-14 04:09:20,550 177 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_dra in module base instead of l10n_cr.
2017-02-14 04:09:20,552 177 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_msc in module base instead of l10n_cr.
2017-02-14 04:09:20,555 177 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating …
```
=> [FIX] l10n_cr: Fix partners title

addons/stock/stock.py
- Activate the MTO route on SO lines
- Activate the route "Buy" on a Product A without quantity on hand, add
a supplier
- Create a SO with 2 lines. First line is Product A, second line is
Product A with route MTO
- Confirm the SO, run the procurement if necessary
- Confirm the PO, receive the products
- On the picking generated from the SO, you should have one line
"Waiting Availability" (the line not MTO) and one line "Available"
(the line MTO).
- Click "Recheck Availability". One reserved quant from line 2 is moved
to line 1.
A trick is to assign first the move with ancestors, so we don't "steal"
the reservation on the other move.
Fixes #15950
opw-725373
=> [FIX] stock: sort moves to do

addons/point_of_sale/point_of_sale.py
9.0 cherry pick 13bba16 point of sale empty picking
Extracted from PR [odoo#16389](https://github.com/odoo/odoo/pull/16389)
DUMMY: [abastotal#172](https://github.com/Vauxoo/abastotal/pull/172)
=> [9.0] Cherry-pick to POS modules from Odoo

addons/purchase/purchase.py
To reproduce, see issue #16611.
In the mentioned use case, a line with a quantity of zero is created,
which generates a traceback at invoice validation.
Fixes #16611
opw-741055
=> [FIX] purchase: zero line

addons/website_sale_options/static/src/js/website_sale.js
Rev 0ff26cf7cdb29bc525462b281d2253889a65b1f4 disabled this option
because it was causing JS errors, which is not the case anymore.
We now get the expected result:
- if product has no variants, open quick add modal dialog
- if the product has variants, open the product page to let
the user choose a variant
Also fix the bootstrap modal bug that happens when the quick add
modal is opened on a product that is not published (modal appeared
partially transparent and unusable)
Dummy pr
https://github.com/Vauxoo/abastotal/pull/216
=> [FIX] website_sale_options: reallow "quick cart add" on product grid

addons/l10n_cr/data/l10n_cr_state_data.xml, doc/cla/corporate/vauxoo.md
Summary
-------------
When installing costa rican localization the partners titles has a wrong reference to base module that cause a warning message in server log. In total the localization had 8 partners titles that not exists in base which was removed the reference and another 2 that exists in base but not had any difference.
Courtesy of Vauxoo.
To fix:
-------
```
2017-05-26 22:14:31,647 137 INFO openerp_template odoo.modules.loading: loading l10n_cr/data/l10n_cr_state_data.xml
2017-05-26 22:14:31,721 137 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_pvt_ltd in module base instead of l10n_cr.
2017-05-26 22:14:31,725 137 WARNING openerp_template odoo.addons.base.ir.ir_model: Creating the ir.model.data res_partner_title_ltd in module …
```
=> [FIX] l10n_cr: wrong reference in partners titles

addons/website_sale/static/src/js/website_sale.js
Temporal Patch
Reverting
https://github.com/odoo/odoo/commit/c8a434306f110bfb5e5ce71609e8e096a850d309
Because the prices is not showed correctly when the product has optional
products configured
Revert this change when fixed following reported issue
https://github.com/odoo/odoo/issues/17342
=> [FIX] Reverting  website_sale: Updating price on Optional Products TA#7904, Issue#4282

addons/l10n_mx/data/fiscal_position_data.xml
Fixed error ```
"External ID not found in the system:
l10n_mx.account_fiscal_position_foreign" while parsing
/home/odoo/odoo-10.0/addons/l10n_mx/data/fiscal_position_data.xml:4
```
runbot.vauxoo.com/runbot/static/build/33575-277-89f985/logs/job_20_test_all.txt
=> [IMP] l10n_mx: Added lost data to fiscal positions

addons/l10n_mx/__manifest__.py
Fiscal positions must be generated before to assign the chart template to generate the files
=> [IMP] l10n_mx: Order data files to assign the fiscal positions

addons/purchase/invoice.py
Setting the taxes in the accounting move entries
is important for the taxes report.
When a price difference occures in a purchase
with a product set in a perpetual inventory valuation,
the taxes set on the price difference move line should be the same
than the move line from which this price difference
is computed. Otherwise, the taxes report
do not have the whole purchase amount
opw-710228
=> [FIX] purchase: taxes in price difference accounting entry

addons/base_address_city/__manifest__.py, addons/base_address_city/models/res_partner.py, addons/base_address_city/views/res_partner_view.xml
Like the address_format could be changed by each country, this method
is required to append the field city_id in the views, to all country
address formats.
But if We need inherit the view to add a parameter in city or city_id,
WE need overwrite this method. Now, with this change, We only inherit
the view, and not all the method.
=> [IMP] base_address_city: Improved way as append the city_id

addons/product/i18n/es.po, addons/product/pricelist_view.xml
The base string "Products Price" was changed to "Products Price List Name" with its respective traduction "Precio de los productos" to "Nombre de tarifa de productos". 
This change is because it's confusing for the customers introduce a name when with the original string, "Products Price", looks like you need to introduce a price.
Issue https://github.com/odoo/odoo/issues/19076
**screen shots**
=> [IMP] product: change string of search field pricelists

addons/im_livechat/controllers/main.py, odoo/addons/base/ir/ir_translation.py
It was decided to do this patch when talking to @moylop260
FIX https://github.com/odoo/odoo/issues/18363
- [  ] TODO- Remove this ugly fix after issue
https://github.com/odoo/odoo/issues/19920 be solved
Odoo Ticket 775568
Also reverted commit [FIX] im_livechat: unsupported locale
https://github.com/odoo/odoo/commit/6879409723184ed360043b7a2da11fcd725e5c4f
DUMMY PR https://github.com/Vauxoo/abastotal/pull/416
=> [FIX] odoo: Temporal patch to`support` spanish Latin America (es_419) lang

addons/base_address_extended/models/base_address_extended.py
This PR fix an issue when you try to use the new fields `'street_name', 'street_number' 'street_number2'`  in address_format from res.country you get error.
=> [10.0][base_address_extended] FIX fields in address_format

addons/point_of_sale/models/pos_order.py
Change invoice_id after create invoice lines and not before. This is
because it can produce an error when there are actions on update
pos.order and the invoice is not complete.
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
https://github.com/odoo/odoo/pull/21334
--
=> [REF] point_of_sale: avoid relating order with not complete invoice

addons/account/models/account_invoice.py, addons/purchase/models/account_invoice.py
It was the purpose of this commit fea667a2433dfc2387daa7051989e840d30e18e0
However it uses purchase uom in any cases and not
only vendor bill.
This commit correct it by using it only if a purchase
order is linked to the invoice.
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
--
=> [FIX] purchase: Only use purchase UOM on vendor bill

addons/point_of_sale/static/src/js/chrome.js, addons/point_of_sale/static/src/js/devices.js, addons/point_of_sale/static/src/js/models.js
This reverts commit 8e63bcb47c72240f5d520f157b0ae5ffa291a714 in order to solved this current error into production instance of the customer for the project "abastotal":
With the revert we try to temporarily solve the problem, once the client can operate we are going to be able to review more carefully what would be the correct solution to the error, removing this change.
[Related issue at vauxoo.com](https://www.vauxoo.com/web#id=4566&view_type=form&model=helpdesk.ticket&action=357&menu_id=249)
=> Revert "[FIX] point_of_sale: IoT https in pos" vx-issue-id#4566

addons/l10n_mx/data/account_tag_data.xml
New account tags were added to use with the incoming of the northern border
zone of Mexico
These changes were announced in the new Annex 24 RFM 2019 [1] and define
the new accounts for the northern border zone. This change affects a
part of the CoA because these accounts are added in the middle instead
of at the end of the group.
[1] https://www.sat.gob.mx/cs/Satellite?blobcol=urldata&blobkey=id&blobtable=MungoBlobs&blobwhere=1461173688346&ssbinary=true
Description of the issue/feature this PR addresses:
Current behavior before PR:
Desired behavior after PR is merged:
--
=> [FIX] l10n_mx: add new changes on COA according with the SAT

openerp/http.py, openerp/service/db.py
In such a case the db filtering won't be applied on an empty regex so
we use the list of databases passed to `db_name` (--database) as
the database list (and we also avoid to list all the databases present
on the postgresql cluster)
As a side effect, this patch allows to strengthen the postgresql
security
by preventing Odoo to list all the databases present on the cluster.
Based on
https://github.com/Vauxoo/odoo/commit/6fa705399bc05d4b0dce5e7181c40a4a5ab8b1c3
--
=> [FIX] http/db: handle case when db_filter is empty in the config file

addons/account/models/account_move.py, addons/account/tests/test_account_move_entry.py, addons/account/tests/test_account_move_in_invoice.py, addons/account/tests/test_account_move_in_refund.py, addons/account/tests/test_account_move_out_invoice.py, addons/account/tests/test_account_move_out_refund.py, addons/account/tests/test_account_move_reconcile.py, addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
Clone of
=
https://github.com/odoo/odoo/pull/94617
Main
-
[FIX] account: Do not attempt to create cash basis entries on non-casn-basis Company
Explain
-
Chances are that Journal Entries are coming from previous migration and they could trigger the creation of CABA Journal Entries even when the company at stake is a a non Cash Basis Company.
--
=> [FIX] account: Do not attempt to create cash basis entries on non-casn-basis Company

requirements.txt
On Debian based systems, the `tzdata` package is maintained to reflect changes in timezones and there is no need to upgrade the `python3-tz` package. On the other hand, for those who are using `pip` and thus our `requirements.txt`, the package needs to be up to date. By unpinning it in the requirements.txt:
- new installations based on pip will be up to date
- older installations based on pip can easily upgrade
- debian based installations have to maintain the tzdata package
- mixed installs like on runbot will rely on Debian tzdata
closes odoo/odoo#117527
---
=> [FIX] requirements.txt: unpin pytz
